### ISSUE TITLE
질문드립니다.

### ISSUE THREAD

**Issue by murphytklee** [taekk1a2a3a/Spring_Lv1_Assignment#1]
1. DTO는 한 번에 하나의 기능 또는 역할을 수행하도록 설계하는 것이 좋다고 하셨는데 잘 이해가 안가서 질문드립니다. 
그렇다면 게시글 생성에 필요한 dto, 수정에 필요한 dto 이렇게 따로 생성하는게 맞는 방식일까요?
-> BoardCreateRequestDto, BoardUpdateRequestDto, ... 이렇게 각각의 기능마다 만들려면 이름이 길어질 수 밖에 없을 것 같은데 어떻게 하는게 효율적인 방법인가요?

**Comment by slsnrnsep** [comment]
안녕하세요 태경님! 물론 각 행위별 역할이 많이 다르다면, DTO를 여러개를 생성하는게 유지관리에 이점이 있는데, 계속 만들자니 이름이 점점 길어지고 패키지가 지저분 해질 수 있습니다. 월요일에 제가 inner class를 사용하여 하나의 클래스에 여러개의 Dto 클래스를 만드는 방법을 잠깐 소개해드렸었는데 이너클래스를 사용해서 다음 프로젝트를 진행해보시는 것은 어떨까요?
```
public class PostRequestDto {

    @Getter
    @NoArgsConstructor
    public static class Create {
        private String title;
    }

    @Getter
    @NoArgsConstructor
    public static class Update {
        private String content;
    }

    @Getter
    @NoArgsConstructor
    public static class Delete {
        private String title;
    }
}
```
사용법은 다음과 같으며 사용시에는 PostRequestDto.Create 또는 PostRequestDto.Update처럼 사용하여 코드간의 응집도를 높일 수 있습니다.
@Getter와 @NoArgsConstructor 를 붙이는 이유에 대해서는 https://ksh-coding.tistory.com/48 글을 참고하시면 좋을 듯합니다.

**Comment by slsnrnsep** [comment]
추가로 1주차과제에서 수정,삭제시에 비밀번호를 @PathVariable로 url에서 받아오도록 하고 계신데, 비밀번호와 같이 보안이 중요한 데이터들에 대해서는 url에서 굳이 노출시킬 필요는 없다고 생각합니다. Update같은 경우에는 requestDto로 통해서 이미 받고 계신데, requestDto필드에 userPw를 넣어서 json으로 받는 방법이 더욱 좋아보입니다!  그 외에는 checkPw하는 공통적인 부분들을 메서드로 따로 빼주신 점은 아주 좋은 것 같습니다. 앞으로도 중복되는 코드를 줄이고 효율적인 방법을 찾으려고 고민하는 시간을 많이 가지면 좋을 것 같습니다

**Comment by murphytklee** [comment]
안녕하세요 정영호 매니저님 ! 피드백 감사합니다.
매니저님 말씀대로 inner class를 사용해서 RequestDto를 분리해보았습니다.
수정과 삭제시에도 개인정보를 json으로 받는 방법으로 변경해보았습니다.

boardid로 조회하는 경우는 pathvariable 로 계속 받고
제목으로 조회하는 경우에는 query로 변경하는게 좋을까요?

**Comment by slsnrnsep** [comment]
태경님 추가질문에 대하여 답변드립니다.
사소한 부분마저도 고민이 되신다는 것은 훌륭한 백엔드 개발자의 자질을 갖추신 것 같습니다.

제 경험상 id와 같은 숫자 형식은 @Pathvariable로 받는 것이 좋고, 제목으로 조회하는 경우라면 한글이 들어갈 수 있기 떄문에 requestDto를 사용할 것 같습니다. url에 한글이 들어간다면 인코딩과정에서의 의도치 않은 결과가 발생할 수 있습니다.

추가로 query파라미터 방식은 주로 검색할떄 사용하는 방식으로 실제로 구글에서 spring이라는 단어로 검색하였을 떄 
https://www.google.com/search?q=spring 처럼 쿼리파라미터 방식을 사용하고 있음을 확인하실 수 있습니다.

헷갈리신다면 실제 우리가 즐겨찾는 페이지들에서는 어떻게 통신하고 있을까? 를 찾아보시면 재미도 있고 많은 참고가 될 것 같습니다.
